site_name: MSIS Prep
site_url: http://msis-prep.alt-tag.com/
site_author: Tom Gregory
site_description: "Preparatory material for prospective Masters of Information Systems students"
repo_url: "https://github.com/tag/msis-prep"
edit_uri: ""

copyright: '© 2020–2021, Tom Gregory<br>Shared under a <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons BY-NC-SA 4.0 license</a>'

theme:
  name: material
  features:
      - instant
  icon:
    logo: material/school
    repo: fontawesome/brands/github

nav:
    - 'index.md'
    - Software Development:
      - 'HTML and Prototyping' : 'prototyping.md'
      - 'Programming' : 'programming.md'
    - Managing Software Projects:
      - 'Waterfall & SDLC' : 'waterfall.md'
      - 'Agile' : 'agile.md'
      - 'Contrasting Agile & Waterfall' : 'agile_waterfall.md'
    - Business Modeling:
      - 'Use Case Diagrams' : 'usecase.md'
      - 'Sequence Diagrams' : 'sequencediagrams.md'
      - 'Data Modeling and SQL' : 'data.md'
    - Enterprise Software:
      - 'IT Controls' : 'it_controls.md'
      - 'ERP - Introduction' : 'ERP.md'
      - 'ERP - Business Cycles' : 'business_cycles.md'
    - 'Network Infrastructure' : 'network_model.md'
    - 'Statistics' : 'statistics.md'

extra_css:
  - "css/styles.css"

markdown_extensions:
    - smarty
    - meta
    - md_in_html
    - abbr
    - toc:
       permalink: false
    - admonition
    - pymdownx.details # Make admonitions collapsable
    - footnotes
    - smarty
    - pymdownx.superfences # Nest codeblocks inside admonitions; prereq for Mermaid
    # - fenced_code
    - pymdownx.mark
    # - mdx_truly_sane_lists
    - mdx_breakless_lists
    - pymdownx.tasklist
    - pymdownx.arithmatex: # Allow embedded Math/LaTeX; see https://squidfunk.github.io/mkdocs-material/reference/mathjax/
        generic: true
    # - pymdownx.critic

    # pygments # Code highlighing
