site_name: MSIS Prep
site_url: http://msis-prep.alt-tag.com/
site_author: Tom Gregory
site_description: "Preparatory material for prospective Masters of Information Systems students"
repo_url: "https://github.com/tag/msis-prep"
copyright: "Â© 2020, Tom Gregory<br>Shared under a [Creative Commons BY-NC-SA 4.0 license](https://creativecommons.org/licenses/by-nc-sa/4.0/)"
theme:
  name: material
  features:
      - instant

      
      - tabs
nav:
    - Home: index.md
    - Modules:
      - 'Programming' : 'programming.md'
      - 'Use Case Diagrams' : 'usecase.md'
      - 'Sequence Diagrams' : 'sequencediagrams.md'
      - 'Data Modeling and SQL' : 'data.md'
      - 'Programming' : 'programming.md'
      - 'Statistics' : 'statistics.md'
      - 'Prototyping' : 'prototyping.md'
      - 'Waterfall Development' : 'waterfall.md'
      - 'Agile': 'agile.md'
      - 'IT Controls' : 'it_controls.md'
      - 'ERP - ERP Intro' : 'ERP.md'
      - 'ERP - Business Cycles' : 'business_cycles.md'

extra_css:
  - "css/styles.css"

markdown_extensions:
    - smarty
    - meta
    - md_in_html
    - abbr
    - toc:
       permalink: true
    - admonition
    - footnotes
    - smarty
    - fenced_code
    - pymdownx.mark
    # - mdx_truly_sane_lists
    - mdx_breakless_lists
    - pymdownx.tasklist
    # - pymdownx.critic

    # pygments # Code highlighing
